// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwREqR5Cd0Ww0iMN2MBeLwfaPW_uNHfj4',
    appId: '1:570792864672:web:84b3200f88d3f0aace92c5',
    messagingSenderId: '570792864672',
    projectId: 'prueba-tecnica-dab57',
    authDomain: 'prueba-tecnica-dab57.firebaseapp.com',
    storageBucket: 'prueba-tecnica-dab57.appspot.com',
    measurementId: 'G-0K708ZJ1H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Ef5zngJd20dppz7gOBsoUFfZaM6xYAU',
    appId: '1:570792864672:android:343d00d38dcc3c99ce92c5',
    messagingSenderId: '570792864672',
    projectId: 'prueba-tecnica-dab57',
    storageBucket: 'prueba-tecnica-dab57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFPB9SHqyYqy282aa94jlTLMnBcd70yQ0',
    appId: '1:570792864672:ios:7f272ec97bb218b5ce92c5',
    messagingSenderId: '570792864672',
    projectId: 'prueba-tecnica-dab57',
    storageBucket: 'prueba-tecnica-dab57.appspot.com',
    iosClientId: '570792864672-pge03b184j6gfbokei5353gr078fgfhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebaTecnicaDashfleet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFPB9SHqyYqy282aa94jlTLMnBcd70yQ0',
    appId: '1:570792864672:ios:7f272ec97bb218b5ce92c5',
    messagingSenderId: '570792864672',
    projectId: 'prueba-tecnica-dab57',
    storageBucket: 'prueba-tecnica-dab57.appspot.com',
    iosClientId: '570792864672-pge03b184j6gfbokei5353gr078fgfhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebaTecnicaDashfleet',
  );
}
